# Generated by Django 4.2.4 on 2023-09-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0002_question_end_date_alter_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
