name: Django CI

on:
  push:
    branches:
      - main
      - iteration2
  pull_request:
    branches:
      - main
      - iteration2
      - iteration3
      - iteration4

env:
  SECRET_KEY: something-secret-key
  ALLOWED_HOSTS: '*.ku.th,localhost,127.0.0.1,::1,testserver'
  TIME_ZONE: Asia/Bangkok

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: [ 3.11 ]
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests polls
        run: |
          python manage.py test polls
